openapi: 3.0.3
info:
  version: 1.0.0
  title: Find your dream job
  description: The API to create and search Jobs
  contact:
    name: Administrator
    email: maximilianorom7@gmail.com
paths:
  /jobs:
    parameters:
    - name: token
      in: header
      description: Bearer token
      required: true
    get:
      description: Get a Job
      responses: 
        200:
          description: Successful Job retrieval
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    description: Job title
                    type: string
                  description:
                    description: Job description
                    type: string
                  client:
                    description: Client
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                      country:
                        type: string
                      timezone:
                        type: string
                  bid:
                    type: object
                    properties:
                      minimum:
                        description: Bid minimum
                        type: integer
                      maximum:
                        description: Bid maximum
                        type: integer
              example:
                title: Sr Python Developer in Django
                description: Looking for a Python Developer
                client:
                  id: 123
                  name: Maximiliano Romay
                  country: Argentina
                  timezone: GMT-3
                bid:
                  minimum: 100
                  maximum: 500
servers:
  - description: Localhost API Server
    url: http://localhost:8000/jobfinder
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/maximilianorom77/DreamJob/1.0.0
