openapi: 3.0.3
info:
  version: 1.0.0
  title: Find your dream job
  description: The API to create and search Jobs
  contact:
    name: Administrator
    email: maximilianorom7@gmail.com
paths:
  /jobs:
    parameters:
    - name: token
      in: header
      description: Bearer token
      required: true
    get:
      description: Get a Job
      responses: 
        200:
          description: Successful Job retrieval
          content:
            application/json:
              schema:
                type: object
                properties:
                  description:
                    description: Job description
                    type: string
              example:
                description: Looking for a Python Developer
servers:
  - description: Localhost API Server
    url: http://0.0.0.0:8000/jobfinder
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/maximilianorom77/DreamJob/1.0.0
